### ISSUE TITLE
Error when installing (already have numpy and visual cpp build tools)

### ISSUE THREAD

**Issue by ammarsufyan** [gatagat/lap#57]
Collecting lap==0.4.0
  Using cached lap-0.4.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "<string>", line 127, in get_numpy_status
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "c:\github\yolov8_bytetrack_supervision\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\github\yolov8_bytetrack_supervision\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\github\yolov8_bytetrack_supervision\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-y0aacoc6\overlay\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-y0aacoc6\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-y0aacoc6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 236, in <module>
        File "<string>", line 220, in setup_package
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xdaybreakerx** [comment]
Lap/Bytetrack doesn't support latest version of Python

Use 3.10.x or less as a workaround

**Comment by gatagat** [comment]
@ammarsufyan & @xdaybreakerx Thanks to @rathaROG, there's a new version of [lap available on PyPI](https://pypi.org/project/lap/) that supports Python up to 3.13. You should be able to install without any issues and without compilation on most of the platforms. Please check and let me know.
